### ISSUE TITLE
FBT Transform doesn't handle TaggedTemplateLiterals

### ISSUE THREAD

**Issue by jrwats** [facebook/fbt#129]
## 🐛 Bug Report

babel-plugin-fbt doesn't deal with Babel AST nodes of `TaggedTemplateLiterals` living in its payload, even within fbt.param.

## To Reproduce

```
html`<div>
  Test three, try fbt auto-params:
  ${ <fbt desc='bold param'><strong>bold</strong></fbt> }
</div>`;
```
and
```
html`<div>
  Test three, try making params manually:
  ${<fbt desc='={bold}'>
      <fbt.param>
       {html`<strong>$
        ${<fbt desc="=bold"><fbt.param>bold</fbt.param></fbt>}
        </strong>` }
     </fbt.param>
   </fbt> }
</div>`
```
Also see the repo below

## Expected behavior

FBT treats tagged template literals similar to how it would a JSX component.  It leaves the AST node alone, and`fbt.param` simply wraps it.

Similarly, for auto-wrapping, we should be able to walk the DOM in the template literal to perform the same logic we do for React JSX.

## Link to repo

https://github.com/schwers/fbt-lit-element-compat

**Comment by kayhadrin** [comment]
I've made a PR toward the repro repo: https://github.com/schwers/fbt-lit-element-compat/pull/2

It fixes fbt parsing issues after updating all fbt-related npm modules.

This compile error still occurs but I've got a feeling it's due to a webpack config issue.

```
[./src/index.jsx] 466 bytes {main} [built] [failed] [1 error]
    + 20 hidden modules

ERROR in ./src/index.jsx 215:78
Module parse failed: Unexpected token (215:78)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       key: "render",
|       value: function render() {
>         return html(_templateObject3(), fbt._("{=bold}", [fbt._param("=bold", <strong>{fbt._("bold", null, {
|             hk: "2C9At4"
|           })}</strong>)], {
ℹ ｢wdm｣: Failed to compile.
```

This happens because there's probably no config to handle a traditional JSX element:

E.g. The code below still generates a compilation error.

```
html`<div>
      blah
      ${
        <strong>bold</strong>
      }
    </div>`;
```

So I'll leave it at this for now.
